"""Base class for TUI mixins.

At runtime the base is MessagePump (provides Textual's metaclass so @on()
handlers are registered).  Type checkers see App as the base plus the custom
attributes that TSDRApp adds, so mixins get full type checking.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from textual.app import App as _Base

    from tsdr.core.events.events import FFTUpdateEvent
    from tsdr.tui.commands.registry import MenuItem
    from tsdr.tui.state import UIState
else:
    from textual.message_pump import MessagePump as _Base


class MixinBase(_Base):  # type: ignore[misc]
    if TYPE_CHECKING:
        ui_state: UIState
        startup_commands: list[str]
        _startup_index: int
        _latest_fft_by_device: dict[str, FFTUpdateEvent]

        def show_status(self, message: str) -> None: ...
        def _show_error(self, message: str) -> None: ...
        def _show_autocomplete(self, commands: list[MenuItem], selected_index: int) -> None: ...
        def _cycle_preview(self, direction: int) -> None: ...
        def _apply_preview(self) -> None: ...
        def _clear_preview(self) -> None: ...
        def _dismiss_autocomplete(self) -> None: ...
        def _open_autocomplete(self) -> None: ...
        def _focus_command_input(self) -> None: ...
        def _blur_command_input(self) -> None: ...
        def _notify_image_mode_changed(self) -> None: ...
        def _tune(self, direction: int, *, coarse: bool = False, fine: bool = False) -> None: ...
        def _adjust_channel_bandwidth(self, direction: int, *, fine: bool = False) -> None: ...
        def _jump_target(self, direction: int) -> None: ...
        def _recall_band(self, key: int) -> None: ...
        def _swap_ab(self) -> None: ...
        def _cycle_step(self, forward: bool) -> None: ...
        def notify_demod_changed(self) -> None: ...
        def _toggle_panel(self, panel: str) -> None: ...
